# Form implementation generated from reading ui file 'qt6/main.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 141)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.input_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.input_btn.setObjectName("input_btn")
        self.gridLayout.addWidget(self.input_btn, 0, 0, 1, 1)
        self.input_path_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_path_line.setText("")
        self.input_path_line.setObjectName("input_path_line")
        self.gridLayout.addWidget(self.input_path_line, 0, 1, 1, 1)
        self.output_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.output_btn.setObjectName("output_btn")
        self.gridLayout.addWidget(self.output_btn, 1, 0, 1, 1)
        self.trim_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.trim_btn.setObjectName("trim_btn")
        self.gridLayout.addWidget(self.trim_btn, 2, 0, 1, 2)
        self.output_path_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_path_line.setText("")
        self.output_path_line.setObjectName("output_path_line")
        self.gridLayout.addWidget(self.output_path_line, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_btn.setText(_translate("MainWindow", "Input folder"))
        self.output_btn.setText(_translate("MainWindow", "Output folder"))
        self.trim_btn.setText(_translate("MainWindow", "Trim"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
